---
title: "Predictive value of traits for ecosystem processes/functions"
output: html_notebook
---

## Description of the project

Several recent papers have suggested that the predictive value of functional traits for ecosystem processes/functions (function used hereafter) is relatively low (e.g. van der Plas et al. 2020). The basis for this claim usually comes from examining the coefficient of determination (r2) when attempting to predict an ecosystem function using a community-level trait (e.g. community weighted mean or functional diversity) using some sort of linear regression framework. In several cases, the r2 value is considered "low" by the authors (often around 0.20 or 0.30, at least for some traits). However, a question that has not been asked is: How much variation in an ecosystem function can we expect a community-level trait to reasonably explain? 

Here, we aim to answer this question by showing that there are fundamental limits to the variation that a community-level trait can explain in community productivity, one of the most commonly studied ecosystem processes (van der Plas 2019). To do this, we use a model that derives plant productivity from growing season length, species' standing biomass, species growing phenology and species maximum relative growth rate (Garnier et al. 2004).

## Methods

Garnier et al. (2004, Ecology) proposed a causal model of aboveground net primary productivity (ANPP, g m-2 day-1). ANPP is defined as the net increase in aboveground biomass per unit area, per time of a community (Shipley et al. 2006, Ecology Letters). Their model writes ANPP as follows:

ANPP = sum(M0ij * (exp(RGRi * (tf - t0)i )-1 )) /dt

where M0ij is the standing biomass of species i in community j, RGRi is the maximum relative growth rate of species i, t0 and tf are the start and finish of species i's growing period and dt is the time interval over which ANPP was measured. This model is thus able to causally derive ANPP at the community level through species' standing biomass, average relative growth rates (RGRi), phenologies (tf and t0)i.

How does this model relate to the plant functional traits that are commonly measured in ecology? The expectation that community-level traits should predict ecosystem functioning is based on the assumption that commonly measured plant functional traits (e.g. SLA, leaf width etc.) are proxies for parameters like plant growth rates (Reich et al. 1992). In this model of ANPP, commonly measured plant functional traits would then be assumed to be correlated to species' RGRs which has been observed (Reich et al. 1992, Vile et al. 2006) or standing biomass (e.g. plant height).

However, just like any complex ecosystem function or process, ANPP does not only depend on species' RGRs. As outlined in the model above, ANPP depends on standing biomass and their phenology (tf and t0)i. These parameters may affect how well commonly measured plant functional traits can predict ecosystem functions. Moreover, the strength of the correlation between RGRs and traits like SLA will also affect predictions of ecosystem processes.

We use Garnier et al.'s (2004) model of ANPP to examine the expected predictive value of community-level traits for ANPP given uncertainty in the relationship between community-level traits and RGR along with variation in species' standing biomasses and phenology. We do this by simulating communities. These communities vary in:

+ 1. The standing biomass of different species in the community
+ 2. The correlation between plant traits (e.g. SLA) and relative growth rate
+ 3. Whether species have similar or different phenologies

In addition, communities vary in the evenness of the their relative abundance distributions.

*How do we vary these parameters?*

The basis of the simulations is to simulate a relative abundance distribution of *sp* species that inhabit *com* communities. The relative abundance distribution of these species in each community is drawn from a Dirichlet distribution with an equal alpha value for each species.

To vary the total standing biomass of all species in a community, we draw a community-level standing biomass value from a normal distribution. The distribution has a mean of 1000 and a variable standard deviation which reflects differences in total standing biomass among communities. Species' relative abundances are multiplied by the total standing biomass to get species-specific standing biomass value for each community.

We then assume that SLA and RGR come from a multivariate normal distribution where we vary the correlation between 0.1 and 0.9 (steps of 0.1). This tells us whether the SLA is a good proxy of RGR.

Finally, we either allow all species to have the same phenology which is equal to *dt*/2. Or we draw the phenological period for each species from a normal distribution: Normal(dt/2, sd). 

In addition, we simulate the best-case scenario for predicting ANPP using community-weighted SLA by simulating the case where SLA and RGR are correlated with 99%, species do not differ in their phenology, there is only one species per community and communities do not vary in their standing biomass. 

## Results

The results of these simulations are plotted below:

```{r}

(p123)

```

By looking at these simulations, three points are immediately clear. First, when there is considerable variation in standing biomass, community weighted mean of SLA is not a good predictor of ln(ANPP). Second, the correlation between SLA and RGR (different colours) matters; the higher the correlation, the better the community weighted mean of SLA explains ln(ANPP). Third, species' variation in phenology matters. The more species vary in their phenology, the worse of a predictor community-weighted mean of SLA is for ln(ANPP).

These results are relatively obvious given the model of ANPP that we used. That model tells us that communities can achieve high levels of ANPP in fundamentally different ways. Communities can:

+ 1. Have species that have very high RGRs
+ 2. Have species that have long phenological periods
+ 3. Have high levels of standing biomass

Assuming (as we have) that SLA is only correlated to RGR means that we will only be able to explain ln(ANPP) under rather restrictive conditions (see Fig above).

## Implications

Many papers are surprised to find low explanatory power of traits on ecosystem functions like ANPP (e.g. van der Plas et al. 2020; Zhang et al. 2022). Our analysis of Garnier et al.'s (2004) model shows that this is not warranted. Traits like SLA are imperfect proxies for things like RGR that are directly connected plant growth. Moreover, other factors like phenology and standing biomass also affect ANPP. Indeed, even when SLA and RGR were highly correlated in our model and differences in standing biomass and phenology among communities was low, the community weighted mean of SLA only explained between 60 and 70% of the variation in ln(ANPP) on average. This is a best-case scenario as we don't consider measurement error in any of the parameters, especially ANPP.

Currently, in the plant ecology literature, we are seeing a trait relationship with an ecosystem process as the end-goal rather than seeing the trait as a useful way to get at a given process in question. The problem with this is that when we find that community-weighted SLA does not explain much variation in productivity, we cannot explain why. Our simple model shows that there is much to be learned by thinking causally about the different processes that determine a given ecosystem processes and how different traits can approximate those processes.

If our model showed that under very good conditions, SLA only predicted ln(ANPP) with accuracies of around 70%, how can we explain cases where SLA does better? (example?). The simplest answer is to say that we did find considerable variation in how well SLA could predict ln(ANPP) so it could simply be chance. However, in our simulations, SLA was only correlated with RGR. It's possible in natural systems that SLA also correlates with environmental conditions, species' standing biomass etc. and so it contains more information about these different parameters. Nonetheless, in our opinion, it's not enough to find that in some cases SLA is a good predictor and in other cases, SLA is not a good predictor. Rather, we want to understand why it is or isn't a good predictor and how we can improve the predictions. We can only do this by understanding the processes that determine a given ecosystem process and how trait values lead to approximations of those processes.

It's important to emphasise that we do not claim that this model of ANPP is "correct". Rather, we are trying to make the point that various different parameters affect ANPP and that many of these will not be well-predicted by, for example, community-weighted leaf traits. Other traits, like plant height, might help approximate standing biomass and traits linked to phenology might also approximate phenology. But, nevertheless, these processes tend to be non-linear so it's generally unlikely that this will fundamentally change these results.

We are also not claiming that we should abandon traits but rather that we should go back to thinking about why we started measuring traits in the first place rather than using them without context for the processes that we trying to approximate.

## Additional notes

There are conditions that we can derive mathematically where the community weighted mean of RGR should be perfectly correlated with SANPP. However, with this model, these conditions are rather limited.

From doing simulations and trying to do the mathematics, I have derived the following conditions.

1. When there is only one species in each community, then the community weighted mean of RGR will be perfectly correlated with SANPP.

We can prove this mathematically as follows:


2. When multiple species are present in a community, the community weighted mean of RGR is calculated as the sum(pi x RGR). In contrast, the SANPP is calculated as as log( sum(pi x exp(RGR x (tf-t0)) ) )/dt. Therefore, rather than multiplying the proportion by the RGR, we multiply it by the exponential of the RGR scaled by the phenological period. Thus, the longer the phenological period is, the greater weight is put on the trait value (RGR) relative to the relative abundance (pi). The consequence of this is that the highest productivity individual species will often be the species with high RGR with a long phenological period rather than the species with the highest relative abundance (pi). In contrast, with a community weighted mean, the relative proportion has a much stronger influence so the community weighted mean generally matches the species' trait value.

This is difficult to prove mathematically but it explains several key observations from the simulations.

+ 1. When the phenological period is very limited (i.e. tf-to is 1 or 2), then the community weighted mean of RGR will be almost perfectly correlated with SANPP. This occurs because then the species that dominates production is very similar to the species that contributes most to the community weighted mean.

+ 2. When there is a perfect rank correlation between species' dominance and RGR, we also get the community weighted mean of RGR to be almost perfectly correlated with SANPP. This is because then species trait values are contributing in similar ways in the community weighted mean and the SANPP.

RGR was estimated based on fresh mass but ANPP is measured in dry mass. If we want to get values that match Garnier et al. 2004, growth rates need to be
on the order of 0.005 and the phenology needs to only be 30 days this makes sense given that this is an RGR max and based on wet-weight in Vile et al. 2006.

We will generally use the ln-transformed productivity as the response variable because sometimes there are cases when the productivity varies on several orders of magnitude. Interestingly, this will often happen when the relative abundance distribution is very skewed. I think this happens because then some communities get very high ANPP if the phenology is long enough (i.e. exponential term in the equation).

















